image: 'atomhub.openatom.cn/amd64/python:3.12-rc'

stages:
  - deps
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - $PIP_CACHE_DIR

install-deps:
  stage: deps
  script:
    - python --version
    - pip install -e ".[dev]"
    - pip list  # 列出已安装的包
  retry:
    max: 2
    when: script_failure
  artifacts:
    paths:
      - ./*  # 保存整个项目目录，包括安装的包

pytest:
  stage: test
  needs: ["install-deps"]
  script:
    - python --version
    - pip list  # 再次列出已安装的包
    - which pytest  # 查找 pytest 的位置
    - pytest --version  # 检查 pytest 版本
    - pytest --junitxml=report.xml --cov=update_whitelist tests/ --cov-report=xml --cov-report=term
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
