image: 'atomhub.openatom.cn/amd64/python:3.12-rc'

stages:
  - deps
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - $PIP_CACHE_DIR

install-deps:
  stage: deps
  script:
    - python --version
    - pip install --upgrade pip
    - pip install -e ".[dev]"
    - pip list
    - which pytest
    - pytest --version
  artifacts:
    paths:
      - ./*
    exclude:
      - .git/
      - .gitlab-ci.yml

pytest:
  stage: test
  needs: ["install-deps"]
  script:
    - python --version
    - pip list
    - which pytest
    - pytest --version
    - pytest --junitxml=report.xml --cov=update_whitelist tests/ --cov-report=xml --cov-report=term
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
