image: 'atomhub.openatom.cn/amd64/python:3.12-rc'

stages:
  - prepare
  - test

variables:
  VENV_PATH: "$CI_PROJECT_DIR/venv"
  GIT_DEPTH: 0

cache:
  paths:
    - .pip-cache/
    - $VENV_PATH

install-deps:
  stage: prepare
  before_script:
    - apt-get update && apit install -y git
  script:
    - python -m venv $VENV_PATH
    - source $VENV_PATH/bin/activate
    - pip install --upgrade pip
    - pip install build  # 添加构建工具
    - python -m build  # 显式构建步骤
    - pip install -e ".[dev]"
    - python -c "from update_whitelist import __version__; print(f'Version: {__version__}')"  # 验证
  artifacts:
    paths:
      - $VENV_PATH
      - update_whitelist/_version.py
    expire_in: 1 hour

test:
  stage: test
  script:
    - source $VENV_PATH/bin/activate
    - cp config.example.yaml config.yaml
    - pip list
    - which pytest
    - pytest --version
    - pytest tests/ --cov=update_whitelist --junitxml=report.xml --cov-report=xml --cov-report=term
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
