image: 'atomhub.openatom.cn/amd64/python:3.12-rc'

stages:
  - prepare
  - test

variables:
  VENV_PATH: "$CI_PROJECT_DIR/venv"

cache:
  paths:
    - .pip-cache/
    - $VENV_PATH

install-deps:
  stage: prepare
  script:
    - python -m venv $VENV_PATH
    - source $VENV_PATH/bin/activate
    - pip install --upgrade pip
    - pip install -e ".[dev]"
  artifacts:
    paths:
      - $VENV_PATH
    expire_in: 1 hour

test:
  stage: test
  script:
    - source $VENV_PATH/bin/activate
    - cp config.example.yaml config.yaml
    - pip list
    - which pytest
    - pytest --version
    - pytest tests/ --cov=update_whitelist --junitxml=report.xml --cov-report=xml --cov-report=term
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
