variables:
  VENV_PATH: "$CI_PROJECT_DIR/venv"

before_script:
  - python -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate

install-deps:
  stage: .pre
  script:
    - pip install --upgrade pip
    - pip install -e ".[dev]"
  artifacts:
    paths:
      - $VENV_PATH
      - update_whitelist/
      - tests/
      - pyproject.toml
    exclude:
      - .git/
      - '**/__pycache__'

test:
  stage: test
  script:
    - source $VENV_PATH/bin/activate
    - pip list
    - which pytest
    - pytest --version
    - pytest tests/ --cov=update_whitelist --junitxml=report.xml --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
