# Create by Abraham Greyson<wechat:abrahamgreyson>
# DateTime 2024/6/13 下午4:10

# 配置文件模板
# 请将此文件复制一份并命名为config.yaml

# 华为云
huawei:
  access_key: your_huawei_access_key
  secret_key: your_huawei_secret_key
  regions:
    - region: huawei_region_code(e.g cn-east-3)
      rules:
        - sg: your_huawei_security_group_id
          allow:
            - port: 80
              desc: http
            - port: 444
              desc: docs
            - port: 5542
              desc: haha
            - port: 33558
    - region: huawei_region_code(e.g cn-east-3)
      rules:
        - sg: your_another_huawei_security_group_id
          allow:
            - port: 7799
              desc: test
            - port: 11111
# 腾讯云
tencent:
  access_key: your_tencent_cloud_access_key
  secret_key: your_tencent_cloud_secret_key
  regions:
    - region: tencent_cloud_region_code(e.g ap-guangzhou)
      rules:
        - sg: your_tencent_security_group_id
          allow:
            - port: 80
              desc: http
            - port: 444
              desc: docs
            - port: 5542
              desc: haha
            - port: 33558

# ipinfo
# 请在 ipinfo.io 申请token
ipinfo:
  tokens:
    - token_a
    - token_b
